### ISSUE TITLE
Add popup notifications for success/errors

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-client#39]
Something in this kind of style:
![image](https://user-images.githubusercontent.com/1864792/176001338-788310ca-e076-49d2-8350-6f3b1e6daa4f.png)

bottom right corner of the page.
Success messages should linger for 3 seconds.
Error messages for 10 seconds.

Stack grows upward.

**Comment by joshplumley** [comment]
@jarrilla  The ability to stack snackbars made me remember this https://material.io/components/snackbars#behavior. This is actually discouraged from a ui perspective. I'm happy to do it, I just wanted to make sure.

**Comment by jarrilla** [comment]
Oh interesting, I wasn't aware of that.
Feel free to modify the requirement to follow recommended practices!

Definitely want to have some sort of notification, though

**Comment by joshplumley** [comment]
TBH, I like the stackable toast messages. The reason is: If you have an error and then an immediate success on some other user action, the error will get replaced to show the success. A user could easily miss it. If you go online you can find good justification for either case. I think a reasonable limit is a good compromise. I just wanted to show you the guidelines incase you had a strong  reason to abide to it. Im game for doing stackable, max of 5 and see how it goes. If we dont like it, we can set the max to 1 and walk away. What do you think?

**Comment by jarrilla** [comment]
Sounds good to me
