### ISSUE TITLE
Shipping History tab bricks when searching by Part

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-client#65]
seraching by Order seems to work correctly

**Comment by jbolles94** [comment]
@jarrilla I can't seem to reproduce this. Are you on a specific branch to get this to happen? Or did you do some specific order of sorting/searching?

**Comment by jarrilla** [comment]
It looks like this might be a backend issue. I'm only seeing it in production right now but server is returning a 500

**Comment by jbolles94** [comment]
@jarrilla I am having a really hard time reproducing this. I have created shipments with new tags from the destination branches and gone back to main and created shipments of all the item types with different item quantities with no success. I have a feeling it is a problem in the `getPopulatedShipmentData` function, but without a test case that I can reproduce this on, it has been hard to put a pin exactly where the problem is. Do you know if your production data for shipments is maybe missing some data needed for the search? Or would you have any other insights into what could be happening here?

**Comment by joshplumley** [comment]
I'm late to the game here but Is it possible that it is related to a specific database entry? To test, @jarrilla could you export your db so that we can import it locally to try and reproduce?

**Comment by jarrilla** [comment]
Sorry, I thought I uploaded screenshots of the console log when I opened this issue.

It is most certainly a data validation thing and I'm actively looking into it now. I apologize for the wasted time on your end--please bill for that as well.

**Comment by jarrilla** [comment]
Update:
The specific documents that bricked this were the following:
```
{
  _id: null,
  items: [ {}, {} ],
  customer: 5e9d8e0f41bd6c1a700d624d,
  orderNumber: 'MIS1070',
  packingSlipId: 'MIS1070-PS1',
  createdBy: 61e702b4d510d20017afd0d8,
  dateCreated: 2022-03-23T19:01:53.515Z,
  shipment: 628cff7f1718a05282f28cdc,
  destination: null
}
{
  _id: null,
  items: [ {}, {} ],
  customer: 5e9d8e0f41bd6c1a700d624d,
  orderNumber: 'MIS1070',
  packingSlipId: 'MIS1070-PS1',
  createdBy: 61e702b4d510d20017afd0d8,
  dateCreated: 2022-03-23T19:01:53.515Z,
  shipment: 628cff7f1718a05282f28cdc,
  destination: null
}
```

It seems there are a number of functions that break down whenever we are assuming `items` exists without null checks.
Most obviously `Shipment History > View` & `Shipment History > Edit`. These do appear to be front-end related, as the entire screen goes blank (react bricks).

So I think we'll have to open a couple of issues. 

Related: https://github.com/conturo-prototyping/pack-ship-server/issues/29
