### ISSUE TITLE
In packing slip queue, searching ignores "Show Fulfilled" check state

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-client#76]
to replicate:
1) uncheck "show fulfilled batches" as to hide batches that have already been fulfilled
2) type something in the search filter, notice that fulfilled batches come back

**Comment by joshplumley** [comment]
@jarrilla, im starting to get into the weeds with this one and came up with a question. What do you want to happen when a user selects a packing slip that has its qty fullfilled AND search string is populated AND the fulfilled check is toggled off? Do you want that selected poacking slip to be removed from the  search results?

I'm asking because, currently if you have a slip checked and you search, the checked slip will persist regardless of the search results (which is the intended behavior). For consistency, I'm thinking we want it to persist when the qty is fullfilled even if the fullfilled check is off, but wanted to hear your thoughts. Let me know

**Comment by jarrilla** [comment]
Hmm good question.

I think we should consider the selection checkbox the primary filter. That is, it should permeate through any other filter. This means that in the case that

This means that if we "un-select" an item that would've otherwise been filtered, then it should get cleared from the grid.

**Comment by joshplumley** [comment]
I didnt understand what you meant by "This means that in the case that". Did something get cut off there?

**Comment by jarrilla** [comment]
It was gonna be the sentence below.. then i got distracted and came back to start the sentence again
